---
title: 'Comparing the Exponential Distribution With The Central Limit Theorem'
author: "Daniel Chacon"
date: "11/22/2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Overview

##Simulations
```{r SetVariables}
lambda <- 0.2
n <- 40
nSim <- 1000
```

```{r Simmulation}
avgMeans <- NULL
for (i in 1 : nSim) {
    sim <- rexp(n,lambda)
    currentAvg <- mean(sim)
    avgMeans <- rbind(avgMeans,currentAvg)
}
hist(avgMeans)
```

##Sample vs Theory
###Mean
```{r MeanComparison}
mean(avgMeans)
1/lambda
```

###Variance
```{r VarianceComparison}
#Observado
sd(avgMeans)
#Esperado se hizo una aprox a la normal por medio del CLT
sqrt((1/lambda)^2/n)
var(avgMeans)[1]

#Esperado se hizo una aprox a la normal por medio del CLT
(1/lambda)^2/n
```

$$N \left(\mu,\frac{\sigma^2}{n}\right)$$
$$\mu = \frac{1}{\lambda}$$
$$\sigma = \frac{1}{\lambda}$$
$$\frac{\left(\frac{1}{\lambda}\right)^2}{n}$$
$$\sqrt\frac{\left(\frac{1}{\lambda}\right)^2}{n}$$
 
###Distribution
